library s;

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';


// Generated by flutter_l10n. Do not edit it.
class S implements WidgetsLocalizations {
  const S();

  @override
  TextDirection get textDirection => TextDirection.ltr;

  static S of(BuildContext context) => Localizations.of<S>(context, S);

  static const LocalizationsDelegate<S> delegate = _Delegate();

  String get AppName => r'Clime App';

  String get Location => r'City';

  String get Temp => r'Temperature';

  String get TempNotAvailable => r'Temp not available';

  String get CelsiusMark => r'°C';

  String get FeelLike => r'Feel Like';

  String get Humidity => r'Humidity';

  String get Sunrise => r'Sunrise';

  String get Sunset => r'Sunset';

  String get Wind => r'Wind Speed';
}

class _Delegate extends LocalizationsDelegate<S> {
  const _Delegate();

  @override
  Future<S> load(Locale locale) {
    return SynchronousFuture<S>(const S());
  }

  @override
  bool isSupported(Locale locale) => true;

  @override
  bool shouldReload(_Delegate old) => false;
}
